<?php
require_once 'app/Mage.php';
umask(0);
Mage::app('default');
 
$store = Mage::app()->getStore();
$website = Mage::app()->getWebsite();
$websiteId = $website->getId();

$options = getopt("", array(
    "email::",
    "password::",
));

$customerData = array_merge(array(
    first_name => 'Sezzle',
    last_name => 'Customer',
    email => 'szl.user@getnada.com',
    password => '1password'
), $options);
  
$address = array(
    'customer_address_id' => '',
    'prefix' => '',
    'firstname' => $customerData['first_name'],
    'middlename' => '',
    'lastname' => $customerData['last_name'],
    'suffix' => '',
    'company' => '', 
    'street' => array(
        '0' => '91Springboard', // this is mandatory
        '1' => 'JP Nagar, 4th Phase' // this is optional
    ),
    'city' => 'Bengaluru',
    'country_id' => 'IN',
    'region' => '', // can be empty '' if no region
    'region_id' => '', // can be empty '' if no region_id
    'postcode' => '560076',
    'telephone' => '123-456-7890',
    'fax' => '',
    'save_in_address_book' => 1
);
  
// check whether the email address is already registered or not
$customer = Mage::getModel('customer/customer')
                ->setWebsiteId($websiteId)
                ->loadByEmail($customerData['email']);
  
/** 
 * if email address already registered, return the error message
 * else, create new customer account
 */
if ($customer->getId()) {
    echo 'Customer with email '. $customerData['email'] .' is already registered.';
} else {
   
    $customer = Mage::getModel('customer/customer');
     
    // $password = $customer->generatePassword(); // you can write your own password here instead of magento generated password
  
    $customer->setWebsiteId($websiteId)
             ->setStore($store)
             ->setFirstname($customerData['first_name'])
             ->setLastname($customerData['last_name'])
             ->setEmail($customerData['email'])
             ->setPassword($customerData['password']);
  
    try {
        // set the customer account as confirmed
        $customer->setForceConfirmed(true);
  
        // save customer
        $customer->save();
  
        $customer->setConfirmation(null);
        $customer->save();
  
        // set customer address
        $customerId = $customer->getId(); 
        $customAddress = Mage::getModel('customer/address');
        $customAddress->setData($address)
                      ->setCustomerId($customerId)
                      ->setIsDefaultBilling('1')
                      ->setIsDefaultShipping('1')
                      ->setSaveInAddressBook('1');
  
        // save customer address
        $customAddress->save();
  
        // // send new account email to customer
        // $storeId = $customer->getSendemailStoreId();
        // $customer->sendNewAccountEmail('registered', '', $storeId);
  
        // // set password remainder email if the password is auto generated by magento
        // $customer->sendPasswordReminderEmail();

        echo 'Customer with email '. $customerData['email'] .' is successfully created.';
    } catch (Mage_Core_Exception $e) {
        Zend_Debug::dump($e->getMessage());
        Mage::log($e->getMessage(), null, $logFile);
 
    } catch (Exception $e) {
        Zend_Debug::dump($e->getMessage());
        Mage::log($e->getMessage(), null, $logFile);
    }
}